<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\*.*"/>
    <Compile Remove="Data\Program.cs"/>
    <None Remove="Data\*.*"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="Spectre.Console.Testing"/>
    <PackageReference Include="Spectre.Verify.Extensions"/>
    <PackageReference Include="Verify.Xunit"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Errata\Errata.csproj"/>
  </ItemGroup>

</Project>
