<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" Version="10.0.201" />
    <PackageVersion Include="MinVer" PrivateAssets="All" Version="7.0.0" />
    <PackageVersion Include="Polyfill" Version="9.24.0" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Spectre.Console" Version="0.57.0" />
    <PackageVersion Include="Spectre.Console.Testing" Version="0.57.0" />
    <PackageVersion Include="Spectre.Verify.Extensions" Version="28.16.0" />
    <PackageVersion Include="Verify.Xunit" Version="31.12.5" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>